repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [ "--profile", "black", "--filter-files" ]
-   repo: https://github.com/google/yapf
    rev: v0.40.1
    hooks:
    -   id: yapf
