name: CI

on:
  push:
    paths:
      - examples/**
      - firefox_bookmarks/**
      - tests/**
      - .gitignore
      - .pre-commit-config.yaml
      - pyproject.toml
      - pytest.ini
  pull_request:
    paths:
      - examples/**
      - firefox_bookmarks/**
      - tests/**
      - .gitignore
      - .pre-commit-config.yaml
      - pyproject.toml
      - pytest.ini

jobs:
  yapf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction
      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction
      - name: Run tests and report coverage
        run: |
          poetry run coverage run --source firefox_bookmarks -m pytest
          poetry run coverage report
