name: Unit Tests

on: [push, pull_request]

jobs:
  run-unit-tests:
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11"]

    name: Unit tests with Python ${{ matrix.python_version }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install Poetry
        id: install-poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        id: poetry-install
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction

      - name: Run tests and report coverage
        id: unit-tests-and-coverage
        run: |
          poetry run coverage run --source firefox_bookmarks -m pytest --ignore=tests/integration_tests/
          poetry run coverage report
